### ISSUE TITLE
Error accessing GameSettings-GameSettings.json

### ISSUE THREAD

**Issue by mluizvitor** [K0lb3/Romancing-SaGa-Re-univerSe-asset-downloader#1]
I'm not familiar with python so I can't help much. I can run the code using Windows 10 and elementaryOS 5.1 but at one point this error happens on both systems.

```
C:\Users\mluiz\Aplicativos\Romancing-SaGa-Re-univerSe-asset-downloader>python download_assets.py
Traceback (most recent call last):
  File "download_assets.py", line 163, in <module>
    main()
  File "download_assets.py", line 43, in main
    update_version(*ver)
  File "download_assets.py", line 63, in update_version
    with open(game_settings_path, "rt", encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\mluiz\\Aplicativos\\Romancing-SaGa-Re-univerSe-asset-downloader\\assets\\gl\\apk_monobehaviours\\GameSettings-GameSettings.json'
```

**Comment by mluizvitor** [comment]
Running in elementaryOS 5.1, Kernel 5.4.0-77, Python 3.6.9, PIP 9.0.1

```
❯ python3.6 download_assets.py
Traceback (most recent call last):
  File "download_assets.py", line 163, in <module>
    main()
  File "download_assets.py", line 43, in main
    update_version(*ver)
  File "download_assets.py", line 63, in update_version
    with open(game_settings_path, "rt", encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/vitor/Aplicativos/Romancing-SaGa-Re-univerSe-asset-downloader/assets/gl/apk_monobehaviours/GameSettings-GameSettings.json'
```

**Comment by K0lb3** [comment]
That's a bit weird,
as the error implies that the extraction of the monobehaviours from the apk failed for one reason or another.
Can you check the content of the assets/gl dir?

In theory there should be a file name current.apk, which is the apk downloaded from qooapp and a folder named apk_monobehaviours that shouldn't be empty.

**Comment by mluizvitor** [comment]
While running "download_assets.py" I checked the folder "assets/gl/apk_monobehaviours" and didn't see files being extracted there. You can see below screenshots of the folders inside "assets". On Windows it's exactly that way.


![Captura de tela de 2021-07-17 13-39-25](https://user-images.githubusercontent.com/57257682/126043816-d9dbfa34-c3a3-4f52-9ab0-88cc85ce0524.png)

![Captura de tela de 2021-07-17 13-38-51](https://user-images.githubusercontent.com/57257682/126043820-c078ce14-cd4e-4e21-a3dc-b1736069468c.png)

**Comment by K0lb3** [comment]
So, the apk download seems to work fine.
That means, that the monobehaviour extraction fails.
This should have printed some errors tho,
so it's pretty weird, especially so, because I tested the script on some systems and it worked everywhere.

I guess the best bet would be cloning the repo again and reinstalling/updating UnityPy.

**Comment by mluizvitor** [comment]
I recorded the step by step and installed UnityPy 1.7.7 and 1.7.8 and cloned the repository again and nothing worked. As you said, the .apk is downloaded normally, but after that the error happens.

https://user-images.githubusercontent.com/57257682/126071194-e0d8ec7a-cde0-4463-829c-17b5cc5749ff.mp4

**Comment by K0lb3** [comment]
Please run the following script within the repo and check the results.
It prints the expected values after the actual values, so it should be able to narrow down the problem.
 
 ```python
 from lib.paths import STRUCTS_PATH, ASSETS
from lib.asset import export_obj
import os
import json
from zipfile import ZipFile
import UnityPy

# 0. setup 
version = "gl"
path = os.path.join(ASSETS, version)
os.makedirs(path, exist_ok=True)
MONOS = os.path.join(path, "apk_monobehaviours")
os.makedirs(MONOS, exist_ok=True)

# 1. load structs as in asset.py
STRUCTS = {}
with open(STRUCTS_PATH, "rt", encoding="utf8") as f:
    STRUCTS.update(json.load(f))
print("Structs:",len(STRUCTS), "/", 6316)

# 2. load apk
apk_f = open(os.path.join(ASSETS, version, "current.apk"), "rb")
zip_f = ZipFile(apk_f)
unity_f = zip_f.open("assets/bin/Data/data.unity3d")
env = UnityPy.load(unity_f)

monobehaviours = []
exports = 0
failed = 0
objects = list(env.objects)
print("Objects:", len(objects), "/", 161813)
for obj in env.objects:
    if obj.type.name == "MonoBehaviour":
        data = obj.read()
        print("Trying to export", obj.path_id, data.name)
        try:
            exports += len(export_obj(obj, MONOS, True))
            monobehaviours.append(data.name)
        except Exception as e:
            print(f"Failed to extract obj {obj.path_id} - {e}")
            failed += 1
zip_f.close()
apk_f.close()

print("Structs:",len(STRUCTS), "/", 6316)
print("Objects:", len(objects), "/", 161813)
print("MonoBehaviours", len(monobehaviours), "/", 52586)
print("Exported", exports, 52586)
print("Failed", failed)
print("Exported GameSettings?", "GameSettings" in monobehaviours)
print("Failed", failed)
```

**Comment by K0lb3** [comment]
Please run the following script within the repo and check the results.
It prints the expected values after the actual values, so it should be able to narrow down the problem.
 
 ```python
 from lib.paths import STRUCTS_PATH, ASSETS
from lib.asset import export_obj
import os
import json
from zipfile import ZipFile
import UnityPy

# 0. setup 
version = "gl"
path = os.path.join(ASSETS, version)
os.makedirs(path, exist_ok=True)
MONOS = os.path.join(path, "apk_monobehaviours")
os.makedirs(MONOS, exist_ok=True)

# 1. load structs as in asset.py
STRUCTS = {}
with open(STRUCTS_PATH, "rt", encoding="utf8") as f:
    STRUCTS.update(json.load(f))
print("Structs:",len(STRUCTS), "/", 6316)

# 2. load apk
apk_f = open(os.path.join(ASSETS, version, "current.apk"), "rb")
zip_f = ZipFile(apk_f)
unity_f = zip_f.open("assets/bin/Data/data.unity3d")
env = UnityPy.load(unity_f)

monobehaviours = []
exports = 0
failed = 0
objects = list(env.objects)
print("Objects:", len(objects), "/", 161813)
for obj in env.objects:
    if obj.type.name == "MonoBehaviour":
        data = obj.read()
        print("Trying to export", obj.path_id, data.name)
        try:
            exports += len(export_obj(obj, MONOS, True))
            monobehaviours.append(data.name)
        except Exception as e:
            print(f"Failed to extract obj {obj.path_id} - {e}")
            failed += 1
zip_f.close()
apk_f.close()

print("Structs:",len(STRUCTS), "/", 6316)
print("Objects:", len(objects), "/", 161813)
print("MonoBehaviours", len(monobehaviours), "/", 52586)
print("Exported", exports, 52586)
print("Failed", failed)
print("Exported GameSettings?", "GameSettings" in monobehaviours)
print("Failed", failed)
```

**Comment by mluizvitor** [comment]
This is what the script returns:

```
❯ python3 script.py
Structs: 6316 / 6316
Objects: 0 / 161813
Structs: 6316 / 6316
Objects: 0 / 161813
MonoBehaviours 0 / 52586
Exported 0 52586
Failed 0
Exported GameSettings? False
Failed 0

```

**Comment by K0lb3** [comment]
That's a bit weird, to say the least.
As it seems, UnityPy fails to load the asset files completely.
Since I can't replicate the problem nor have much time within the next 3 weeks,
I can't really help you for now. Sorry.
